// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © supermortalcoil
// https://www.binance.com/en/futures/funding-history/0
//
// Funding Rate = Premium Index + clamp ( Interest Rate - Premium Index, 0.05%, -0.05% )
//
// Average Premium Index (P) = (1*Premium_Index_1+2*Premium_Index_2+3*Premium_Index_3+···+·480*Premium_index_480) / (1+2+3+···+480)
// 
// *Premium_Index_1: the premium index at the first minute
//
//
//
//@version=5


indicator("My Script")

// Helpers
clamp(num, min, max) => math.min(math.max(num, min), max)

bool isFundingBar = ((hour == 0 or hour == 8 or hour == 16) and (minute == 0)) or timeframe.isdwm

interestRate = 0.01
mmr = 0.4

// Premium Index
//p = request.security("BINANCE:BTCUSDT_PREMIUM", "", close)*100 // correct value in %
premium = request.security("BINANCE:BTCUSDT_PREMIUM", "1", close)*100

new_funding_period = ta.change(time("480")) != 0

var int n = na
var float premium_sum = na
var int n_sum = na

if new_funding_period
    n := 1
    premium_sum := premium
    n_sum := 1
else
    n += 1
    premium_sum += premium * n
    n_sum += n

predicted_TWAP = premium_sum / n_sum

current_TWAP = ta.valuewhen(new_funding_period, predicted_TWAP[1], 0)

// Time Weighted Moving Average
// twap(source, length) =>
//     norm = 0.0
//     sum = 0.0
//     for i = 1 to length+1
//         weight = i * source
//         norm := norm + weight
//         sum := sum + source[i] * weight
//     sum / norm

// Funding Rate

f = current_TWAP + clamp(interestRate-premium, -0.05, 0.05) 

// Capped Funding Rate

// floor = -0.75 * mmr
// cap = 0.75 * mmr

// cF = clamp(f, floor, cap)

//b = ta.barssince()
//plot(p, title="Premium Index", style=plot.style_histogram, linewidth=5, color=color.orange)
plot(isFundingBar ? f : na, title="Funding Rate", style=plot.style_histogram, linewidth=5, color= color.blue)